### ISSUE TITLE
question on w:\ drive

### ISSUE THREAD

**Issue by chisan0501** [HaroldMitts/wininstall#8]
according to the script, there were multiple line that calls w:\ and I did not find any related info at the documentation,

I tried renaming the w:\ to e:\ (which is same drive that stores script and wim) but no luck, getting access denied error

I ended up creating a 3rd partition and assigned a driver letter w:\ , everything works.

my question :

is w:\ drive meant to be network drive? 
is creating a 3rd partition necessary?

**Comment by HaroldMitts** [comment]
The script assigns temporary drive letters, while running in WinPE;

- S for System 
- W for Windows
- R for Recovery

You can find these getting assigned in the :SetFirmware section when the echo commands build up the temporary diskpart answer files.

These drive letters are assigned only during WinPE and when the PC reboots to Windows, the driver letters get assigned as usual, with the System partition and recovery partition drive letters being removed and hidden, 

This methodology is created by Microsoft using their sample scripts, which I adopted to build wininstall.cmd as a single file, instead of many separate scripts and answer files. You can find reference here: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/system-builder-deployment-of-windows-10-for-desktop-editions#deploy-the-image-to-new-computers-windows-installation and you can download the original scripts and answer files (found in USB-B) from here: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/system-builder-deployment-of-windows-10-for-desktop-editions#deploy-the-image-to-new-computers-windows-installation

Creating 3rd partition would be recovery partition, if you count System partition as 1st partition and Windows as 2nd.

**Comment by chisan0501** [comment]
got cha, thanks for the explaination.
